### ISSUE TITLE
Details for PCB

### ISSUE THREAD

**Issue by wes1993** [fabrizioromanelli/Pellet-Stove-Control#1]
Hello,
thanks a lot for PCB projects, could you give me some information why there are different files?

Best regards
Stefano

**Comment by fabrizioromanelli** [comment]
> Hello, thanks a lot for PCB projects, could you give me some information why there are different files?
> 
> Best regards Stefano

Sure!
The backup folder inside the PCB folder is just a backup from previous work, you can just ignore it.
All the other files (.kicad*) are used by the KiCAD software to store all the details related to the PCB layers.
Hope this could help! Also, I have some spare PCBs. If you need any, send me an email.
