### ISSUE TITLE
Esphome

### ISSUE THREAD

**Issue by goldrake1981** [fabrizioromanelli/Pellet-Stove-Control#2]
C'è un modo per collegarla a esphome ? 
Grazie

**Comment by fabrizioromanelli** [comment]
Se esphome supporta MQTT, allora il collegamento è semplice e si può fare.

**Comment by goldrake1981** [comment]
Cercavo un modo comodo per installarla su home assistant, soprattutto qualcosa che potesse permettermi di aggiornare il codice con semplicità . Solo che non sono in grado.  Pensavo ci fosse qualche esempio .

**Comment by fabrizioromanelli** [comment]
Capisco, prima bisognerebbe installare la parte del firmware su ESP e poi interfacciare la scheda con Home Assistant

**Comment by goldrake1981** [comment]
Devo studiare.  Ne so veramente poco e niente.
